name: Publish to Docker registry
description: Published the Docker image to the regostry
inputs:
  docker_image_name:
    description: "Docker image name"
    required: true
  docker_custom_tag:
    description: "Custom tag for Docker image"
    required: false
    default: ''
  docker_add_latest_tag:
    description: 'Specifies if "latest" tag is added to Firefox based image'
    required: false
    default: 'true'
  docker_use_git_tag_as_tag:
    description: "Specifies if git tag is added to Docker tag"
    required: true
    default: 'true'
  docker_tag_suffix:
    description: "Specifies if custom suffix is added to a Docker tag"
    required: false
    default: ''
  docker_dockerfile_path:
    description: "Specifies path to dockerfile"
    required: false
    default: 'dockerfile'
  docker_context:
    description: "Specifies docker context"
    required: false
    default: '.'
runs:
  using: "composite"
  steps:
    - name: Get current git tag
      shell: bash
      run: |
        CURRENT_GIT_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
        echo "CURRENT_GIT_TAG=$CURRENT_GIT_TAG" >> $GITHUB_ENV
    - name: Prepare Docker tags
      id: prepare_docker_tags
      uses: L-Sypniewski/github-create-docker-tags-action@v1.1.0
      env:
        IMAGE_NAME: ${{ inputs.docker_image_name }}
        docker_add_latest_tag: ${{ inputs.docker_add_latest_tag }}
        USE_GIT_TAG: ${{ inputs.use_git_tag_as_docker_tag }}
        CURRENT_GIT_TAG: ${{ env.CURRENT_GIT_TAG }}
        docker_custom_tag: ${{ inputs.docker_custom_tag }}
        PROJECT_NAME: ${{ github.repository_owner }}
        CUSTOM_SUFFIX: ${{ inputs.docker_tag_suffix }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CONTAINER_REGISTRY_PAT }}
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: ${{ runner.os }}-buildx-
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        file: ${{ inputs.docker_dockerfile_path }}
        context: ${{ inputs.docker_context }}
        push: true
        tags: ${{ steps.prepare_docker_tags.outputs.tags }}
        platforms: linux/amd64
        labels: "org.opencontainers.image.source=https://github.com/${{ github.repository }}"
        build-args: |
          BASE_IMAGE=runtime-deps
          NUGET_SOURCE=https://nuget.pkg.github.com/TwentyFiveDev-L-Sypniewski/index.json
          SELF_CONTAINED=true
          NUGET_USER=TwentyFiveDev-L-Sypniewski
        secrets: |
          "nugetpassword=${{ secrets.CONTAINER_REGISTRY_PAT }}"
