name: Add reviewdog comments and Run tests on PR creation or when commited to the PR
on:
  workflow_call:
    inputs:
      dotnet_version:
        description: "dotnet version"
        type: string
        required: true
      reviewdog_action_version:
        description: "Reviewdog composite action version to be used by workflow"
        type: string
        required: true
      codeclimate_action_version:
        description: "CodeClimate composite action version to be used by workflow"
        type: string
        required: true
      reviewdog_version:
        description: "Reviewdog version"
        type: string
        required: true
      reviewdog_dotnet_build_flags:
        description: "Flags appended to dotnet build command"
        type: string
        required: false
      reviewdog_reporter:
        description: "Reporter type"
        type: string
        required: true
      reviewdog_level:
        description: "Level (info, warning, error)"
        type: string
        required: false
        default: error
      codeclimate_reporter_id:
        description: "CodeClimate reporter ID"
        type: string
        required: true
      codeclimate_test_reporter_version:
        description: "Version of CodeClimate's test reporter to be used for uploading coverage data"
        type: string
        required: false
        default: latest
      project_relative_path:
        description: "Relative path to the .sln or .csproj file, used as a parameter for 'dotnet test' command. Not needed if .sln or .csproj file is in the root folder of a repository"
        type: string
        required: false
      treat_warnings_as_errors:
        description: "If true 'dotnet build' command fails should there are be any errors"
        type: boolean
        required: false
        default: false

permissions:
  contents: write
  packages: write
  pull-requests: write
jobs:
  review-code-test-and-upload-coverage:
    name: Review code, run tests and upload coverage
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.dotnet_version }}
          dotnet-quality: "ga"
      - name: Run reviewdog
        uses: L-Sypniewski/ReusableWorkflows/actions/lint-with-reviewdog@${{ inputs.reviewdog_action_version }}
        with:
          reviewdog_version: ${{ inputs.reviewdog_version }}
          reporter: ${{ inputs.reviewdog_reporter }}
          dotnet_build_flags: ${{ inputs.reviewdog_dotnet_build_flags }}
          level: ${{ inputs.reviewdog_level }}
          project_relative_path: ${{ inputs.project_relative_path }}
          github_token:  ${{ secrets.GITHUB_TOKEN }}
      - name: Upload coverage
        uses: L-Sypniewski/ReusableWorkflows/actions/test-and-upload-coverage@${{ inputs.codeclimate_action_version }}
        with:
          codeclimate_reporter_id: ${{ inputs.codeclimate_reporter_id }}
          codeclimate_test_reporter_version: ${{ inputs.codeclimate_test_reporter_version }}
          project_relative_path: ${{ inputs.project_relative_path }}
          treat_warnings_as_errors: ${{ inputs.treat_warnings_as_errors }}