name: Run tests on PR creation or when commited to the PR
on:
  workflow_dispatch:
    inputs:
      dotnet_version:
        description: "Dotnet version used for setup-dotnet action"
        required: true
        type: string
      code_climate_reporter_id:
        description: "CodeClimate reporter ID"
        required: true
        type: string
      code_climate_test_reporter_version:
        description: "Version of CodeClimate's test reporter to be used for uploading coverage data"
        required: false
        type: string
        default: latest
      test_project:
        description: "Relative path to the .sln or .csproj file, used as a parameter for 'dotnet test' command. Not needed if .sln or .csproj file is in the root folder of a repository"
        required: false
        type: string
      treat_warnings_as_errors:
        description: "If true 'dotnet build' command fails should there are be any errors"
        required: false
        default: false
        type: boolean
  workflow_call:
    inputs:
      dotnet_version:
        description: "Dotnet version used for setup-dotnet action"
        required: true
        type: string
      code_climate_reporter_id:
        description: "CodeClimate reporter ID"
        required: true
        type: string
      code_climate_test_reporter_version:
        description: "Version of CodeClimate's test reporter to be used for uploading coverage data"
        required: false
        type: string
        default: latest
      test_project:
        description: "Relative path to the .sln or .csproj file, used as a parameter for 'dotnet test' command. Not needed if .sln or .csproj file is in the root folder of a repository"
        required: false
        type: string
      treat_warnings_as_errors:
        description: "If true 'dotnet build' command fails should there are be any errors"
        required: false
        default: false
        type: boolean
permissions:
  contents: write
  packages: write
  pull-requests: write
jobs:
  reviewdog:
    name: Lint code with reviewdog
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: reviewdog/action-setup@v1
        id: setup-reviewdog
        if: github.event.pull_request.state != 'closed'
        with:
          reviewdog_version: v0.14.1
      - name: Run reviewdog
        if: steps.setup-reviewdog.outcome != 'skipped'
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # msbuild is used to avoid duplicated errors - summary is not displayed: https://stackoverflow.com/a/44780004/8297552
          dotnet msbuild | reviewdog -f=dotnet -reporter=github-pr-review -level warning -fail-on-error
  run-tests:
    name: "Run tests and upload coverage to CodeClimate"
    if: github.event.pull_request.merged == true || github.event.pull_request.state != 'closed'
    runs-on: ubuntu-22.04
    steps:
      - name: Set ENV for codeclimate (pull_request)
        if: github.event_name == 'pull_request' && github.event.pull_request.merged == false
        # Needed as: When the action is triggered by a pull_request event, GitHub will squash and merge this branch with the base branch, generating a new commit, thus a new hash.
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/$GITHUB_HEAD_REF:refs/remotes/origin/$GITHUB_HEAD_REF
          echo "GIT_BRANCH=$GITHUB_HEAD_REF" >> $GITHUB_ENV
          echo "GIT_COMMIT_SHA=$(git rev-parse origin/$GITHUB_HEAD_REF)" >> $GITHUB_ENV
      - name: Set ENV for codeclimate (push)
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
        run: |
          echo "GIT_BRANCH=$GITHUB_HEAD_REF" >> $GITHUB_ENV
          echo "GIT_COMMIT_SHA=$GIT_COMMIT_SHA" >> $GITHUB_ENV
      - name: Set ENV for codeclimate (workflow dispatch)
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "GIT_BRANCH=$GITHUB_REF_NAME" >> $GITHUB_ENV
          echo "GIT_COMMIT_SHA=$GIT_COMMIT_SHA" >> $GITHUB_ENV
      - name: Run tests and upload coverage
        env:
          CC_TEST_REPORTER_ID: ${{ inputs.code_climate_reporter_id }}
        run: |
          # Download codeclimate test reporter
          curl -L "https://codeclimate.com/downloads/test-reporter/test-reporter-${{ inputs.code_climate_test_reporter_version }}-linux-amd64" > ./codeclimate-test-reporter
          chmod +x ./codeclimate-test-reporter

          # Install dotnet tools to merge coverage files
          dotnet tool install -g dotnet-reportgenerator-globaltool

          # Start codeclimate process
          ./codeclimate-test-reporter before-build

          # Build solution
          dotnet build /p:TreatWarningsAsErrors="${{ inputs.treat_warnings_as_errors }}"
          dotnet test ${{ inputs.test_project }} --collect:"XPlat Code Coverage" --settings runsettings.xml

          reportgenerator -reports:"./**/coverage.cobertura.xml" -targetdir:"./coverage" -reporttypes:"lcov"  

          ./codeclimate-test-reporter after-build -t lcov --exit-code $?
